### ISSUE TITLE
Do you know how to load arrays of data?

### ISSUE THREAD

**Issue by davidmartinezros** [mehmetbajin/angular-i18n-l10n-demo#1]
I'm doing a web and I want to load an array of projects

"data":
    [
    {
    "id": 1, "titol": "BBB",
    "tema": "Angular2",
    "tipus": "Example",
    "data": "10/07/2016",
    "estat": "FINISHED",
    "link": "http://davidmartinezros.com/Angular2/HelloWorld/",
    "html": "My first Angular2 Component that prints something into screen (<b>'Hello World'</b>).",
    "repositori": "https://github.com/davidmartinezros/HolaAngular2"
    },
...

Do you know if ngx-translate could access to {{ 'data[0].titol' | translate }} ?

And how to do it?

Thanks in advanced,

David

**Comment by mehmetbajin** [comment]
Looks like this has been discussed in this issue:

https://github.com/angular-translate/angular-translate/issues/1508
